#pragma config(Motor,  port2,           M_Wheel_L2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           M_Wheel_R2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           M_Wheel_R1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           M_Wheel_L1,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(1200)

#include "Vex_Competition_Includes.c"

void move(int V, int H, int X){
	motor[M_Wheel_R2] = V - H;
	motor[M_Wheel_R1] = V - H;
	motor[M_Wheel_L2] = V + H;
	motor[M_Wheel_L1] = V + H;
}

void pre_auton(){

}

task autonomous(){

}

task usercontrol()
{  int V, H;
	while(true){
		V = vexRT[Ch3];
		H = vexRT[Ch1];

		if(abs(V) < 15) V = 0;
		if(abs(H) < 15) H = 0;
		move(V, H, 0);
	}
}
